# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Accord < Formula
  desc "Consumer-driven contract testing using plain YAML files"
  homepage "https://github.com/andrewh/accord"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andrewh/accord/releases/download/v0.2.0/accord_0.2.0_darwin_amd64.tar.gz"
      sha256 "07b0e930ea61374c2ca0d9ef4fea1b79fb6be4ccb6f79aac0dff67e8c5494b0b"

      def install
        bin.install "accord"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andrewh/accord/releases/download/v0.2.0/accord_0.2.0_darwin_arm64.tar.gz"
      sha256 "2706a6c2f5e675ccd76ee71cf0b7a2d7850c4c53a7ab2e0110719ae3e6356d0a"

      def install
        bin.install "accord"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrewh/accord/releases/download/v0.2.0/accord_0.2.0_linux_amd64.tar.gz"
      sha256 "6d081dfb5de1dddbcf61cf42e1443a5f6d0f29b6945103711c14a420cfeebd78"
      def install
        bin.install "accord"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrewh/accord/releases/download/v0.2.0/accord_0.2.0_linux_arm64.tar.gz"
      sha256 "2e2ddd75598b1eae7924033f149a3527ea0eab652974a84518fb7ed97ed3cd69"
      def install
        bin.install "accord"
      end
    end
  end
end
