# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Accord < Formula
  desc "Consumer-driven contract testing using plain YAML files"
  homepage "https://github.com/andrewh/accord"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andrewh/accord/releases/download/v0.1.1/accord_0.1.1_darwin_amd64.tar.gz"
      sha256 "9b65706902f7b81700ea326ec2a115897d6bbff0834f3819b84e32ef09779015"

      def install
        bin.install "accord"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andrewh/accord/releases/download/v0.1.1/accord_0.1.1_darwin_arm64.tar.gz"
      sha256 "710616fd411de0f9993226811e0bfc359ff5d8c8e1088ebc57d2811068c08392"

      def install
        bin.install "accord"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrewh/accord/releases/download/v0.1.1/accord_0.1.1_linux_amd64.tar.gz"
      sha256 "095754b0459979a054b29c271defc8551022e8541f477a03b458e8a284e348d5"
      def install
        bin.install "accord"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrewh/accord/releases/download/v0.1.1/accord_0.1.1_linux_arm64.tar.gz"
      sha256 "8e63592dbfe753bdf8eec42dd8850f10ecf9f2bca69eb7f72ec737c0319dce4f"
      def install
        bin.install "accord"
      end
    end
  end
end
