# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Accord < Formula
  desc "Consumer-driven contract testing using plain YAML files"
  homepage "https://github.com/andrewh/accord"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andrewh/accord/releases/download/v0.2.1/accord_0.2.1_darwin_amd64.tar.gz"
      sha256 "663ff30b13eba15514475be4f982ddaea634fd2a186f50949f35f3f1baa9a7d8"

      def install
        bin.install "accord"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andrewh/accord/releases/download/v0.2.1/accord_0.2.1_darwin_arm64.tar.gz"
      sha256 "204bf11c87951a2c8c3c0ef139ad7e27eb1f8cba4b60e4433f2d05cf1ca6e35c"

      def install
        bin.install "accord"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrewh/accord/releases/download/v0.2.1/accord_0.2.1_linux_amd64.tar.gz"
      sha256 "f136e82002a5a2d2215e51b7857b01dcafc87a5e37ad4910866321df08fc61d1"
      def install
        bin.install "accord"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrewh/accord/releases/download/v0.2.1/accord_0.2.1_linux_arm64.tar.gz"
      sha256 "e085015f4179f729738199393c1efc1ee70191173a3c2e024dfb3ac752536db9"
      def install
        bin.install "accord"
      end
    end
  end
end
