# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Motel < Formula
  desc "Synthetic telemetry generator for OpenTelemetry"
  homepage "https://github.com/andrewh/motel"
  version "0.5.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andrewh/motel/releases/download/v0.5.1/motel_0.5.1_darwin_amd64.tar.gz"
      sha256 "13cc2720c8394a880b5f5d0da7143e0772ff49381df9cef99406d0c1bd783c6b"

      define_method(:install) do
        bin.install "motel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andrewh/motel/releases/download/v0.5.1/motel_0.5.1_darwin_arm64.tar.gz"
      sha256 "57f065e188e74c48bdaca07e4cad8c00962c82b7e25a640e28924ba98e63602e"

      define_method(:install) do
        bin.install "motel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrewh/motel/releases/download/v0.5.1/motel_0.5.1_linux_amd64.tar.gz"
      sha256 "0b62ed29803ed1d776d89eb79fe86cbb6bdcb630376a9e799fd8baa05ca36784"
      define_method(:install) do
        bin.install "motel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrewh/motel/releases/download/v0.5.1/motel_0.5.1_linux_arm64.tar.gz"
      sha256 "e114877c35c778201d4340e34ae1306c00fb469372e975ce0f7271f7b816dffe"
      define_method(:install) do
        bin.install "motel"
      end
    end
  end
end
