# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Motel < Formula
  desc "Synthetic OpenTelemetry generator"
  homepage "https://github.com/andrewh/motel"
  version "0.9.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andrewh/motel/releases/download/v0.9.2/motel_0.9.2_darwin_amd64.tar.gz"
      sha256 "bd45ab874690a14be991cdfbafcd8fa113249495d02958676f492d2c402d0232"

      define_method(:install) do
        bin.install "motel"
        man1.install "man/man1/motel.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andrewh/motel/releases/download/v0.9.2/motel_0.9.2_darwin_arm64.tar.gz"
      sha256 "5e7253873642d08950ca11d7d9ab8042a8dbac202cd89629defea6a0840605cd"

      define_method(:install) do
        bin.install "motel"
        man1.install "man/man1/motel.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrewh/motel/releases/download/v0.9.2/motel_0.9.2_linux_amd64.tar.gz"
      sha256 "309b8899cb458dd837b1f4fd5bd804d7f5b40cbf9ea43eedc83dd6f9ccfa66eb"
      define_method(:install) do
        bin.install "motel"
        man1.install "man/man1/motel.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrewh/motel/releases/download/v0.9.2/motel_0.9.2_linux_arm64.tar.gz"
      sha256 "bf2d2fe891fa69c4c0be60c6c1a912afa10eb83392184435a8dd99d5c69f84c2"
      define_method(:install) do
        bin.install "motel"
        man1.install "man/man1/motel.1"
      end
    end
  end
end
