# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Motel < Formula
  desc "Synthetic telemetry generator for OpenTelemetry"
  homepage "https://github.com/andrewh/motel"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andrewh/motel/releases/download/v0.2.0/motel_0.2.0_darwin_amd64.tar.gz"
      sha256 "346c3275f5b124a17ca0678a791af7ae17bb6199821712f25a5241c41a7a6c37"

      def install
        bin.install "motel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andrewh/motel/releases/download/v0.2.0/motel_0.2.0_darwin_arm64.tar.gz"
      sha256 "060a0d271ea6e0e54823bd4af670a5848cbe17e8568fd0be9ffe490375c8c11b"

      def install
        bin.install "motel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrewh/motel/releases/download/v0.2.0/motel_0.2.0_linux_amd64.tar.gz"
      sha256 "6ffd162f5bb45d3c3ccb52dfee1f1842b27def2ed7bec2e5af117a9eab214113"
      def install
        bin.install "motel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrewh/motel/releases/download/v0.2.0/motel_0.2.0_linux_arm64.tar.gz"
      sha256 "ad63d3f6f97a52e33776fbbb2c3cdf9a713a090f4219c8f51c7de0be3b5dcd11"
      def install
        bin.install "motel"
      end
    end
  end
end
