# This file was generated by GoReleaser. DO NOT EDIT.
cask "olaf" do
  name "olaf"
  desc "CLI-first automation framework with human-in-the-loop approval gates"
  homepage "https://github.com/andrewh/olaf"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "olaf"

  on_macos do
    on_intel do
      url "https://github.com/andrewh/olaf/releases/download/v#{version}/olaf_#{version}_darwin_amd64.tar.gz"
      sha256 "4a376de420cd61581311db5bc8748ae6f450f6b194b072549e8ab6ec027753ad"
    end
    on_arm do
      url "https://github.com/andrewh/olaf/releases/download/v#{version}/olaf_#{version}_darwin_arm64.tar.gz"
      sha256 "1b1bf71d9fd2ef36fb8e691536850eac9acc7268784ea68f53f45161b5828eb1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andrewh/olaf/releases/download/v#{version}/olaf_#{version}_linux_amd64.tar.gz"
      sha256 "9eb446e21b6b5b632d5ee3e1d3f585ef6142ef0b9022ef3c88040d98a5cbb3f0"
    end
    on_arm do
      url "https://github.com/andrewh/olaf/releases/download/v#{version}/olaf_#{version}_linux_arm64.tar.gz"
      sha256 "20b1f8a430b52dc2eecd563bc095271cb202adc924b995c553724c7314bff1fc"
    end
  end

  # No zap stanza required
end
